### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by wensleyoliv** [Mysterken/DLsiteMetadata#2]
Thank you for making this extension.
When i try to download metadata i get the error in the image, i utilize my Playnite in Brazilian Portuguese, however, I put it in English just to make it easier to identify the error, strangely parts of the error still appear in Portuguese, they say: value cannot be null and name of the parameter: source.
If there is any way to log this please tell me because I don't know how.
![image](https://github.com/Mysterken/DLsiteMetadata/assets/14226926/25efbc06-e0d4-4974-a823-3dc95ecffa23)

**Comment by Mysterken** [comment]
Hi @wensleyoliv  thanks for the issue,

The logs should be commonly located in the path `%AppData%\Playnite`.
There should be both `playnite.log` and `extensions.log` files, the error logs are written to those. (I am not sure which one in our case).

If you find the error log please send them back here.

**Comment by wensleyoliv** [comment]
> Hi @wensleyoliv thanks for the issue,
> 
> The logs should be commonly located in the path `%AppData%\Playnite`. There should be both `playnite.log` and `extensions.log` files, the error logs are written to those. (I am not sure which one in our case).
> 
> If you find the error log please send them back here.

Thank you i found them.
[extensions.log](https://github.com/user-attachments/files/15538490/extensions.log)
[playnite.log](https://github.com/user-attachments/files/15538492/playnite.log)

**Comment by Mysterken** [comment]
Thanks, will investigate this.

**Comment by Mysterken** [comment]
Alright @wensleyoliv this should be fixed in this new version, please check and tell me me if there's still any issues.

[DLsiteMetadata_db03c8d9-645a-4359-aafb-01cda945f301_1_0_1.zip](https://github.com/user-attachments/files/15551031/DLsiteMetadata_db03c8d9-645a-4359-aafb-01cda945f301_1_0_1.zip)

Based on change from this PR: https://github.com/Mysterken/DLsiteMetadata/pull/3

**Comment by wensleyoliv** [comment]
> Alright @wensleyoliv this should be fixed in this new version, please check and tell me me if there's still any issues.
> 
> [DLsiteMetadata_db03c8d9-645a-4359-aafb-01cda945f301_1_0_1.zip](https://github.com/user-attachments/files/15551031/DLsiteMetadata_db03c8d9-645a-4359-aafb-01cda945f301_1_0_1.zip)
> 
> Based on change from this PR: #3

Unfortunately still not fixed, it gives me the same error.
[extensions.log](https://github.com/user-attachments/files/15568059/extensions.log)
[playnite.log](https://github.com/user-attachments/files/15568060/playnite.log)

**Comment by Mysterken** [comment]
I've made a minor adjustment, tell me if this work:

[DLsiteMetadata_db03c8d9-645a-4359-aafb-01cda945f301_1_0_1.zip](https://github.com/user-attachments/files/15568418/DLsiteMetadata_db03c8d9-645a-4359-aafb-01cda945f301_1_0_1.zip)

**Comment by wensleyoliv** [comment]
It works perfectly thank you very much, im gonna close the issue now. Just something to add, the extension does not find metadata for a lot of my H games, maybe it has to do with the category of some of them being video on DLsite, but it also did not find metadata for other RPGs too, maybe something like pasting the link of the page you want to pull the metadata would be useful in the future too, but i'm not gonna bother you with that.
